[Details]
  Icon = "burnfix.svg"
  Name = "Burn Fix"
  ID = "io.github.vinser.burnfix"
  Version = "1.0.0"
  Build = 0

[LinuxAndBSD]
  GenericName = "Burn Fix"
  Categories = ["Accessory"]
  Comment = "Fix LCD and LED retensions and burn-in, look for bad pixels"
  Keywords = ["burn-in", "retension", "monitor", "TV", "display"]
